<?php

namespace Autoload;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../../src/Autoload/Autoload.php';

use Autoload\Autoload;

/**
 * Test class for Autoload.
 * Generated by PHPUnit on 2010-09-24 at 14:34:13.
 */
class AutoloadTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var Autoload
   */
  protected $object;

  /**
   * @ver Reflection
   */
  protected $reflector;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new Autoload;
    
    $this->reflector = new \ReflectionObject($this->object);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }

  /**
   * @todo Implement testSetNamespaceSeparator().
   */
  public function testSetNamespaceSeparator() {
    $this->object->setNamespaceSeparator('test');

    $ns = $this->reflector->getProperty('namespaceSeparator');
    $ns->setAccessible('true');

    $this->assertEquals('test', $ns->getValue($this->object));
  }

  /**
   * @todo Implement testGetNamespaceSeperator().
   */
  public function testGetNamespaceSeperator() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testSetFileExtension().
   */
  public function testSetFileExtension() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testGetFileExtension().
   */
  public function testGetFileExtension() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testGetRegisteredNamespaces().
   */
  public function testGetRegisteredNamespaces() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testRegisterNamespace().
   */
  public function testRegisterNamespace() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testRegisterNamespaces().
   */
  public function testRegisterNamespaces() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testRegister().
   */
  public function testRegister() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testUnregister().
   */
  public function testUnregister() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testLoadClass().
   */
  public function testLoadClass() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

}

?>
